name: Build connectors for BI tools

on:
  push:
    paths:
      - 'bi-connectors/PowerBIConnector/**'
      - 'bi-connectors/TableauConnector/**'
      - '.github/workflows/bi-connectors.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Pack Tableau JDBC connector
      id: pack-tableau-jdbc
      run: |
        zip -r opensearch_sql_jdbc.taco . -x *.taco
      working-directory: bi-connectors/TableauConnector/opensearch_sql_jdbc
    - name: Prepare Power BI ODBC connector
      run: |
        cp OpenSearchProject-ODBC.pq OpenSearchProject-ODBC.m
      working-directory: bi-connectors/PowerBIConnector
    - name: Pack Power BI ODBC connector
      id: pack-powerbi-odbc-os-proj
      run: |
        zip OpenSearchProject-ODBC.mez *.png *.m *.resx *.pqm
      working-directory: bi-connectors/PowerBIConnector
    - name: Prepare Power BI ODBC connector for 'Amazon OpenSearch Service'
      id: prep-powerbi-odbc-amz-os-svc
      run: |
        sed -i 's/<value>OpenSearch Project<\/value>/<value>Amazon OpenSearch Service<\/value>/g' resources.resx
        sed -i 's/Documentation.Name = "OpenSearchProject-ODBC"/Documentation.Name = "AmazonOpenSearchService-ODBC"/g' OpenSearchProject-ODBC.m
        sed -i 's/section #"OpenSearchProject-ODBC";/section #"AmazonOpenSearchService-ODBC";/' OpenSearchProject-ODBC.m
        sed -i 's/\[DataSource.Kind="OpenSearchProject-ODBC", Publish="OpenSearchProject-ODBC.Publish"\]/[DataSource.Kind="AmazonOpenSearchService-ODBC", Publish="AmazonOpenSearchService-ODBC.Publish"]/g' OpenSearchProject-ODBC.m
        sed -i 's/OpenSearchProject-ODBC.Contents/AmazonOpenSearchService-ODBC.Contents/g' OpenSearchProject-ODBC.m
        sed -i 's/OpenSearch.Publish/AmazonOpenSearchService-ODBC.Publish/g' OpenSearchProject-ODBC.m
        sed -i 's/OpenSearch.Icons/AmazonOpenSearchService-ODBC.Icons/g' OpenSearchProject-ODBC.m
        sed -i 's/OpenSearchImpl/AmazonOpenSearchServiceImpl/g' OpenSearchProject-ODBC.m
        sed -i 's/OpenSearchType/AmazonOpenSearchServiceType/g' OpenSearchProject-ODBC.m
        sed -i 's/OpenSearch = \[/AmazonOpenSearchService-ODBC = [/' OpenSearchProject-ODBC.m
       sed -i 's/"opensearchproject-odbc"/"amazonopensearchservice-odbc"/g' OpenSearchProject-ODBC.m
      working-directory: bi-connectors/PowerBIConnector
    - name: Pack Power BI ODBC connector for 'Amazon OpenSearch Service'
      id: pack-powerbi-odbc-amz-os-svc
      run: |
        zip AmazonOpenSearchService-ODBC.mez *.png *.m *.resx *.pqm
      working-directory: bi-connectors/PowerBIConnector
    - name: Upload Tableau JDBC connector
      if: steps.pack-tableau-jdbc.outcome == 'success'
      uses: actions/upload-artifact@v2
      with:
        name: TableauConnectors
        path: bi-connectors/TableauConnector/opensearch_sql_jdbc/opensearch_sql_jdbc.taco
    - name: Upload Power BI ODBC connectors
      if: steps.pack-powerbi-odbc-os-proj.outcome == 'success' || (steps.prep-powerbi-odbc-amz-os-svc.outcome == 'success' && steps.pack-powerbi-odbc-amz-os-svc.outcome == 'success')
      uses: actions/upload-artifact@v2
      with:
        name: PBIConnectors
        path: 'bi-connectors/PowerBIConnector/*.mez'
