name: Build connectors for BI tools

on:
  push:
    paths:
      - 'bi-connectors/PowerBIConnector/**'
      - 'bi-connectors/TableauConnector/**'
      - '.github/workflows/bi-connectors.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Pack Tableau JDBC connector
      id: pack-tableau-jdbc
      run: |
        zip -r opensearch_sql_jdbc.taco . -x *.taco
      working-directory: bi-connectors/TableauConnector/opensearch_sql_jdbc
    - name: Prepare Power BI ODBC connector for 'OpenSearch Project'
      run: |
        cp OpenSearchProject.pq OpenSearchProject.m
      working-directory: bi-connectors/PowerBIConnector
    - name: Pack Power BI ODBC connector
      id: pack-powerbi-odbc-os-proj
      run: |
        zip OpenSearchProject.mez *.png *.m *.resx *.pqm
      working-directory: bi-connectors/PowerBIConnector
    - name: Prepare Power BI ODBC connector for 'Amazon OpenSearch Service'
      id: prep-powerbi-odbc-amz-os-svc
      run: |
        mv OpenSearchProject.m AmazonOpenSearchService.m
        sed -i 's/<value>OpenSearch Project<\/value>/<value>Amazon OpenSearch Service<\/value>/g' resources.resx
        sed -i 's/Documentation.Name = "OpenSearch Project"/Documentation.Name = "Amazon OpenSearch Service"/g' AmazonOpenSearchService.m
        sed -i 's/section OpenSearchProject;/section AmazonOpenSearchService;/' AmazonOpenSearchService.m
        sed -i 's/\[DataSource.Kind="OpenSearchProject", Publish="OpenSearchProject.Publish"\]/[DataSource.Kind="AmazonOpenSearchService", Publish="AmazonOpenSearchService.Publish"]/g' AmazonOpenSearchService.m
        sed -i 's/OpenSearchProject.Contents/AmazonOpenSearchService.Contents/g' AmazonOpenSearchService.m
        sed -i 's/OpenSearchProject.Publish/AmazonOpenSearchService.Publish/g' AmazonOpenSearchService.m
        sed -i 's/OpenSearchProjectImpl/AmazonOpenSearchServiceImpl/g' AmazonOpenSearchService.m
        sed -i 's/OpenSearchProjectType/AmazonOpenSearchServiceType/g' AmazonOpenSearchService.m
        sed -i 's/OpenSearchProject = \[/AmazonOpenSearchService = [/' AmazonOpenSearchService.m
        sed -i 's/"opensearchproject-odbc"/"amazonopensearchservice-odbc"/g' AmazonOpenSearchService.m
        sed -i 's/(dsr) => "OpenSearch Project"/(dsr) => "Amazon OpenSearch Service"/g' AmazonOpenSearchService.m
      working-directory: bi-connectors/PowerBIConnector
    - name: Pack Power BI ODBC connector for 'Amazon OpenSearch Service'
      id: pack-powerbi-odbc-amz-os-svc
      run: |
        zip AmazonOpenSearchService.mez *.png *.m *.resx *.pqm
      working-directory: bi-connectors/PowerBIConnector
    - name: Upload Tableau JDBC connector
      if: steps.pack-tableau-jdbc.outcome == 'success'
      uses: actions/upload-artifact@v2
      with:
        name: TableauConnectors
        path: bi-connectors/TableauConnector/opensearch_sql_jdbc/opensearch_sql_jdbc.taco
    - name: Upload Power BI ODBC connectors
      if: steps.pack-powerbi-odbc-os-proj.outcome == 'success' || (steps.prep-powerbi-odbc-amz-os-svc.outcome == 'success' && steps.pack-powerbi-odbc-amz-os-svc.outcome == 'success')
      uses: actions/upload-artifact@v2
      with:
        name: PBIConnectors
        path: 'bi-connectors/PowerBIConnector/*.mez'
