name: Build connectors for BI tools

on:
  push:
    paths:
      - 'bi-connectors/PowerBIConnector/**'
      - 'bi-connectors/TableauConnector/**'
      - '.github/workflows/bi-connectors.yml'

jobs:
  build:
    runs-on: ubuntu-latest
#    defaults:
#      run:
#        working-directory: sql-odbc
    steps:
    - uses: actions/checkout@v1
    - name: Pack Tableau ODBC connector
      run: |
        zip -r opensearch_sql_odbc.taco . -x *.taco
      working-directory: bi-connectors/TableauConnector/opensearch_sql_odbc
    - name: Prepare Power BI ODBC connector
      run: |
        cp SqlOdbcPBIConnector.pq SqlOdbcPBIConnector.m
      working-directory: bi-connectors/PowerBIConnector
    - name: Pack Power BI ODBC connector
      run: |
        zip OpenSearch-project.mez *.png *.m *.resx *.pqm
      working-directory: bi-connectors/PowerBIConnector
    - name: Prepare the second Power BI ODBC connector
      run: |
        sed -i 's/<value>OpenSearch<\/value>/<value>Amazon OpenSearch Service<\/value>/g' resources.resx
        sed -i 's/Documentation.Name = "OpenSearch"/Documentation.Name = "Amazon OpenSearch Service"/g' SqlOdbcPBIConnector.m
      working-directory: bi-connectors/PowerBIConnector
    - name: Pack Power BI ODBC connector for 'Amazon OpenSearch Service'
      run: |
        zip Amazon-OpenSearch-Service.mez *.png *.m *.resx *.pqm
      working-directory: bi-connectors/PowerBIConnector
    - name: Upload Tableau ODBC connector
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: TableauConnector
        path: bi-connectors/TableauConnector/opensearch_sql_odbc/opensearch_sql_odbc.taco
    - name: Upload Power BI ODBC connectors
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: PBIConnectors
        path: 'bi-connectors/PowerBIConnector/*.mez'
