name: Link Checker

on:
  pull_request:
    types: [opened, reopened]
  push:
    branches:
      - 'main'
      - '[1-9]+.[0-9x]+'
      - '[1-9]+.[0-9x]+.[0-9x]+'
    paths:
      - '**/*.pdf'
      - '**/*.pnj'
      - '**/*.jpg'
      - '**/*.json'
      - '**/*.md'
      - '**/*.txt'
      - '**/*.rst'

jobs:
  linkchecker:

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: lychee Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@master
        with:
          args: --accept=200,403,429,999  "./**/*.html" "./**/*.md" "./**/*.txt" --exclude "http://localhost*" "https://localhost" "https://odfe-node1:9200/" "https://community.tableau.com/docs/DOC-17978" ".*family.zzz" "https://pypi.python.org/pypi/opensearchsql/" "opensearch*" ".*@amazon.com" ".*email.com" "git@github.com" "http://timestamp.verisign.com/scripts/timstamp.dll" ".*/PowerBIConnector/bin/Release"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Fail if there were link errors
        run: exit ${{ steps.lychee.outputs.exit_code }}
