name: SQL Java CI

on:
  pull_request:
  push:
    branches-ignore:
      - 'dependabot/**'
    paths:
      - '**/*.java'
      - '**/*.g4'
      - '!sql-jdbc/**'
      - '**gradle*'
      - '**lombok*'
      - '**checkstyle*'
      - 'integ-test/**'
      - '**/*.jar'
      - '**/*.pom'
      - '.github/workflows/sql-test-and-build-workflow.yml'

jobs:
  build:
    strategy:
      # Run all jobs
      fail-fast: false
      matrix:
        entry:
          - { os: ubuntu-latest, java: 17 }
    runs-on: ${{ matrix.entry.os }}

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.entry.java }}

    - name: Build with Gradle
      run: ./gradlew --continue build ${{ matrix.entry.os_build_args }}
