name: SQL Java CI

on:
  pull_request:
  push:
    branches-ignore:
      - 'dependabot/**'
    paths:
      - '**/*.java'
      - '**/*.g4'
      - '!sql-jdbc/**'
      - '**gradle*'
      - '**lombok*'
      - '**checkstyle*'
      - 'integ-test/**'
      - '**/*.jar'
      - '**/*.pom'
      - '.github/workflows/sql-test-and-build-workflow.yml'

jobs:
  build:
    strategy:
      # Run all jobs
      fail-fast: false
      matrix:
        entry:
          - { os: ubuntu-latest, java: 11, os_build_args: -x doctest -x jacocoTestReport  }
    runs-on: ${{ matrix.entry.os }}

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.entry.java }}

    - name: Build with Gradle
      run: ./gradlew --continue integ-test:integTest

    - name: Copy test result file
      run: |
        mkdir test-folder
        mkdir test-folder/legacy
        mkdir test-folder/sql1
        mkdir test-folder/sql2
        mkdir test-folder/ppl
        cp integ-test/build/test-results/integTest/TEST-org.opensearch.sql.legacy.*.xml test-folder/legacy
        cp integ-test/build/test-results/integTest/TEST-org.opensearch.sql.sql.[A-M]*.xml test-folder/sql1
        cp integ-test/build/test-results/integTest/TEST-org.opensearch.sql.sql.[N-Z]*.xml test-folder/sql2
        cp integ-test/build/test-results/integTest/TEST-org.opensearch.sql.ppl.*.xml test-folder/ppl
      if: always()

    - name: Legacy Test Summary
      uses: test-summary/action@v2
      with:
        output: legacy-test-summary.md
        paths: test-folder/legacy/*.xml
      if: always()

    - name: Upload legacy test summary
      uses: actions/upload-artifact@v3
      with:
        name: legacy-test-summary
        path: legacy-test-summary.md
      if: always()

    - name: SQL Test Summary 1
      uses: test-summary/action@v2
      with:
        output: sql-test-summary1.md
        paths: test-folder/sql1/*.xml
      if: always()

    - name: Upload SQL test summary 1
      uses: actions/upload-artifact@v3
      with:
        name: sql-test-summary1
        path: sql-test-summary1.md
      if: always()

    - name: SQL Test Summary 2
      uses: test-summary/action@v2
      with:
        output: sql-test-summary2.md
        paths: test-folder/sql2/*.xml
      if: always()

    - name: Upload SQL test summary 2
      uses: actions/upload-artifact@v3
      with:
        name: sql-test-summary2
        path: sql-test-summary2.md
      if: always()

    - name: PPL Test Summary
      uses: test-summary/action@v2
      with:
        output: ppl-test-summary.md
        paths: test-folder/ppl/*.xml
      if: always()

    - name: Upload PPL test summary
      uses: actions/upload-artifact@v3
      with:
        name: ppl-test-summary
        path: ppl-test-summary.md
      if: always()

    - name: Compile Results
      run: |
        touch test-summary.md
        echo -e "### Legacy Test Results\n" > test-summary.md
        head -c 150 legacy-test-summary.md | cut -d'>' -f1 >> test-summary.md
        echo -e "> \n\n### SQL.[A-M] Test Results\n" >> test-summary.md
        head -c 150 sql-test-summary1.md | cut -d'>' -f1 >> test-summary.md
        echo -e "> \n\n### SQL.[N-Z] Test Results\n" >> test-summary.md
        head -c 150 sql-test-summary2.md | cut -d'>' -f1 >> test-summary.md
        echo -e "> \n\n### PPL Test Results\n" >> test-summary.md
        head -c 150 ppl-test-summary.md | cut -d'>' -f1 >> test-summary.md
        echo -e ">" >> test-summary.md
      if: always()

    - name: Upload Compiled Results
      uses: actions/upload-artifact@v3
      with:
        name: test-summary
        path: test-summary.md
      if: always()
