name: SQL CLI Test and Build

on:
  pull_request:
    types: [opened, reopened]
  push:
    branches-ignore:
      - 'dependabot/**'
    paths:
      - 'sql-cli/**'
      - '.github/workflows/sql-cli-test-and-build-workflow.yml'

jobs:
  build:

    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: sql-cli
    strategy:
      matrix:
        python-version: [3.8]
        opensearch-version: [ 2.2.1 ]

    steps:
      - name: Checkout SQL CLI
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
          pip install setuptools wheel
      
        # tests are designed to run against http://localhost:9200, so we have to disable/remove security plugin
      - name: Download and run OpenSearch
        run: |
          wget -q https://artifacts.opensearch.org/releases/bundle/opensearch/${{ matrix.opensearch-version }}/opensearch-${{ matrix.opensearch-version }}-linux-x64.tar.gz
          tar xf opensearch-${{ matrix.opensearch-version }}-linux-x64.tar.gz
          opensearch-${{ matrix.opensearch-version }}/bin/opensearch-plugin remove opensearch-security
          opensearch-${{ matrix.opensearch-version }}/bin/opensearch -d

      - name: Run Tox Testing
        run: tox

      - name: Build Artifact
        run: python setup.py sdist bdist_wheel

      - name: Create Artifact Path
        run: |
          mkdir -p opensearchsql-builds
          cp -r ./dist/*.tar.gz ./dist/*.whl opensearchsql-builds/

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: opensearchsql
          path: sql-cli/opensearchsql-builds
