name: SQL Java CI

on:
  pull_request:
  push:
    branches-ignore:
      - 'dependabot/**'
    paths:
      - '**/*.java'
      - '**/*.g4'
      - '!sql-jdbc/**'
      - '**gradle*'
      - '**lombok*'
      - '**checkstyle*'
      - 'integ-test/**'
      - '**/*.jar'
      - '**/*.pom'
      - '.github/workflows/sql-test-and-build-workflow.yml'

jobs:
  build:
    strategy:
      # Run all jobs
      fail-fast: false
      matrix:
        entry:
          - { os: ubuntu-latest, java: 11, os_build_args: -x doctest -x jacocoTestReport  }
    runs-on: ${{ matrix.entry.os }}

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.entry.java }}

    - name: Build with Gradle
      run: ./gradlew --continue integ-test:integTest --tests "org.opensearch.sql.sql.QueryIT.*"

    - name: Include only results in xml files
      run: |
        sed -i '2!d' integ-test/build/test-results/integTest/*.xml && echo "</testsuite>" | tee -a integ-test/build/test-results/integTest/*.xml
      if: always()

    - name: Test Summary
      uses: test-summary/action@v2
      with:
        paths: |
          integ-test/build/test-results/integTest/**.xml
      if: always()

    - name: Upload test summary
      uses: actions/upload-artifact@v3
      with:
        name: test-summary
        path: test-summary.md
      if: always()

    - name: Upload xml file
      uses: actions/upload-artifact@v3
      with:
        output: QueryIT.xml
        path: integ-test/build/test-results/integTest/TEST-org.opensearch.sql.sql.QueryIT.xml
      if: always()