name: SQL Java CI

on:
  pull_request:
  push:
    branches-ignore:
      - 'dependabot/**'
    paths:
      - '**/*.java'
      - '**/*.g4'
      - '!sql-jdbc/**'
      - '**gradle*'
      - '**lombok*'
      - '**checkstyle*'
      - 'integ-test/**'
      - '**/*.jar'
      - '**/*.pom'
      - '.github/workflows/sql-test-and-build-workflow.yml'

jobs:
  build:
    strategy:
      # Run all jobs
      fail-fast: false
      matrix:
        entry:
          - { os: ubuntu-latest, java: 11, os_build_args: -x doctest -x jacocoTestReport  }
    runs-on: ${{ matrix.entry.os }}

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.entry.java }}

    - name: Build with Gradle
      run: |
        if [[ ! -e /home/runner ]]; then
          useradd -m -g root -s /bin/bash runner
          chmod -R g+rwx /root
          chmod -R 777 .
        fi
        su runner -m -c './gradlew --continue integ-test:integTest --tests "org.opensearch.sql.legacy.*"'

    - name: Copy test result file
      run: |
        mkdir test-folder
        cp integ-test/build/test-results/integTest/TEST-org.opensearch.sql.legacy.*.xml test-folder
      if: always()

    - name: Legacy Test Summary
      uses: test-summary/action@v2
      with:
        output: legacy-test-summary.md
        paths: test-folder/TEST-org.opensearch.sql.legacy.*.xml
      if: always()
