  Skip to content
    Search or jump to…
    Pull requests
    Issues
    Marketplace
    Explore
    
    @MitchellGale-BitQuill
    opensearch-project
    /
    sql
    Public
    Code
    Issues
    202
    Pull requests
    12
    Actions
    Projects
    2
    Wiki
    Security
    Insights
    sql/.github/workflows/sql-workbench-test-and-build-workflow.yml
    @kavithacm
    kavithacm version bump to 2.1.0 and gradle version bump
    …
    Latest commit edd75a9 27 days ago
    History
    12 contributors
    @davidcui1225@joshuali925@chloe-zh@ps48@kavithacm@dai-chen@dependabot@zhongnansu@penghuo@eugenesk24@vamsi-amazon@Tengda-He
    66 lines (52 sloc)  1.79 KB

  name: SQL Workbench Test and Build

  on: [pull_request, push]

  env:
    PLUGIN_NAME: query-workbench-dashboards
    OPENSEARCH_VERSION: 'main'
    OPENSEARCH_PLUGIN_VERSION: 2.1.0.0

  jobs:

    build:

      runs-on: ubuntu-latest

      steps:
        - name: Checkout Plugin
          uses: actions/checkout@v1

        - name: Checkout OpenSearch Dashboards
          uses: actions/checkout@v1
          with:
            repository: opensearch-project/Opensearch-Dashboards
            ref: ${{ env.OPENSEARCH_VERSION }}
            path: OpenSearch-Dashboards

        - name: Setup Node
          uses: actions/setup-node@v2
          with:
            node-version-file: "../OpenSearch-Dashboards/.nvmrc"
            registry-url: 'https://registry.npmjs.org'

        - name: Move Workbench to Plugins Dir
          run: |
            mv workbench ../OpenSearch-Dashboards/plugins
        - name: OpenSearch Dashboards Plugin Bootstrap
          uses: nick-invision/retry@v1
          with:
            timeout_minutes: 60
            max_attempts: 3
            command: cd ../OpenSearch-Dashboards/plugins/workbench; yarn osd bootstrap

        - name: Test
          run: |
            cd ../OpenSearch-Dashboards/plugins/workbench
            yarn test:jest --coverage
        - name: Upload coverage
          uses: codecov/codecov-action@v1
          with:
            flags: query-workbench
            directory: ../OpenSearch-Dashboards/plugins/workbench
            token: ${{ secrets.CODECOV_TOKEN }}

        - name: Build Artifact
          run: |
            cd ../OpenSearch-Dashboards/plugins/workbench
            yarn build
            mv ./build/*.zip ./build/${{ env.PLUGIN_NAME }}-${{ env.OPENSEARCH_PLUGIN_VERSION }}.zip
        - name: Upload Artifact
          uses: actions/upload-artifact@v1
          with:
            name: workbench
            path: ../OpenSearch-Dashboards/plugins/workbench/build
