name: SQL Plugin Tests

on:
  pull_request:
  push:
    branches-ignore:
      - 'dependabot/**'
    paths:
      - '**/*.java'
      - '**/*.g4'
      - '!sql-jdbc/**'
      - '**gradle*'
      - '**lombok*'
      - '**checkstyle*'
      - 'integ-test/**'
      - '**/*.jar'
      - '**/*.pom'
      - '.github/workflows/sql-test-and-build-workflow.yml'

jobs:
  build:
    strategy:
      # Run all jobs
      fail-fast: false
      matrix:
        entry:
          - { os: ubuntu-latest, java: 11, os_build_args: -x doctest -x jacocoTestReport  }
    runs-on: ${{ matrix.entry.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Test Summary
        uses: test-summary/action@v2
        with:
          paths: |
            results.xml
        if: always()

      - name: Upload test summary
        uses: actions/upload-artifact@v3
        with:
          name: test-summary
          path: test-summary.md
        if: always()
